### PR TITLE
7.22 + pcre2

### PR DESCRIPTION
**Pull request by ScottBailey**
Update to 7.22
Add pcre2-posix library.

### CODE REVIEW

**Comment by jezdez** [comment]
@ScottBailey Any insights what's causing the build failures?

**Comment by ScottBailey** [comment]
> @ScottBailey Any insights what's causing the build failures?

I had some issues with dependencies in local vs global scope for multi-ouptut recipes. If I had time, I think I'd rework this recipe, but it's good enough.

**Comment by ScottBailey** [comment]
The windows issue needs a bit more time than I have today.

**Comment by ScottBailey** [comment]
@chenghlee @jezdez This is ready for a review and maybe some testing?

**Review by cbouss — APPROVED** [review]
LGTM!

**Pull request merged**
